#!/usr/bin/env bash
set -u

BASE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$BASE_DIR" || exit

REPORT_DIR="artifacts"
REPORT_FILE="$REPORT_DIR/ci_routing_report.md"
mkdir -p "$REPORT_DIR"

OUTPUT=""
PYTEST_STATUS=0
POLICY_HASH=""

if command -v pytest >/dev/null 2>&1; then
  OUTPUT=$(pytest -q tests/test_routing_golden_set.py -s 2>&1) || PYTEST_STATUS=$?
else
  PYTEST_STATUS=127
  OUTPUT="pytest not found"
fi

if command -v python >/dev/null 2>&1; then
  POLICY_HASH=$(PYTHONPATH=src python - <<'PY'
from __future__ import annotations

try:
    from policy_engine import load_policy_snapshot
    snapshot = load_policy_snapshot()
    policy_hash = snapshot.get("policy_hash")
    print(policy_hash or "")
except Exception:
    print("")
PY
  )
fi

TOTAL=$(echo "$OUTPUT" | sed -n 's/^Golden cases: //p')
SUMMARY=$(echo "$OUTPUT" | sed -n 's/^Shadow mismatch summary: //p')

if [ "$PYTEST_STATUS" -ne 0 ]; then
  {
    echo "# CI Routing Report"
    echo ""
    echo "routing_report_version: 1"
    if [ -n "$POLICY_HASH" ]; then
      echo "policy_hash: $POLICY_HASH"
    else
      echo "policy_hash: (missing)"
    fi
    echo ""
    echo "- Status: no report generated (tests failed)"
    echo "- Pytest exit code: $PYTEST_STATUS"
    echo ""
    echo "## Pytest output (tail)"
    echo "\`\`\`"
    echo "$OUTPUT" | tail -n 50
    echo "\`\`\`"
    echo ""
    echo "(Generated by scripts/routing_report.sh)"
  } > "$REPORT_FILE"

  echo "Routing report: tests failed; wrote $REPORT_FILE"
  exit 0
fi

{
  echo "# CI Routing Report"
  echo ""
  echo "routing_report_version: 1"
  if [ -n "$POLICY_HASH" ]; then
    echo "policy_hash: $POLICY_HASH"
  else
    echo "policy_hash: (missing)"
  fi
  echo ""
  if [ -n "$TOTAL" ]; then
    echo "- Golden cases: $TOTAL"
  else
    echo "- Golden cases: (missing)"
  fi
  if [ -n "$SUMMARY" ]; then
    echo "- Shadow mismatch summary: $SUMMARY"
  else
    echo "- Shadow mismatch summary: (missing)"
  fi
  echo ""
  echo "(Generated by scripts/routing_report.sh)"
} > "$REPORT_FILE"

echo "Wrote $REPORT_FILE"
